//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EONBussiness.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdanhmuctt
    {
        public int ID { get; set; }
        public string tendanhmuc { get; set; }
        public string hinhanh { get; set; }
        public string tukhoa { get; set; }
        public string mota { get; set; }
        public string alias { get; set; }
        public Nullable<bool> hienthi { get; set; }
    }
}
