//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EONBussiness.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLienHe
    {
        public int ID { get; set; }
        public string tenkhach { get; set; }
        public string email { get; set; }
        public string dienthoai { get; set; }
        public string daichi { get; set; }
        public string chude { get; set; }
        public string noidung { get; set; }
        public Nullable<System.DateTime> ngaygui { get; set; }
        public Nullable<bool> xuly { get; set; }
        public Nullable<System.DateTime> ngayxuly { get; set; }
        public string noidungxl { get; set; }
    }
}
