//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EONBussiness.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSetup
    {
        public int ID { get; set; }
        public string trusochinh { get; set; }
        public string vanphong { get; set; }
        public string dienthoai { get; set; }
        public string hotline { get; set; }
        public string email { get; set; }
        public string tenlienhe { get; set; }
        public string emaillienhe { get; set; }
        public string dienthoailienhe { get; set; }
        public string fb { get; set; }
        public string yt { get; set; }
        public string lk { get; set; }
        public string maps { get; set; }
        public Nullable<int> viewus { get; set; }
        public string mst { get; set; }
        public string congthuong { get; set; }
    }
}
